----------------------------------------------------CREATION OF USER -----------------------------------------------
CREATE USER ONNOVACION IDENTIFIED BY "12345";
GRANT CONNECT TO ONNOVACION;
GRANT CREATE SESSION TO ONNOVACION;
GRANT CREATE ANY TABLE TO ONNOVACION;
GRANT UNLIMITED TABLESPACE TO ONNOVACION;
GRANT RESOURCE TO ONNOVACION;
ALTER USER ONNOVACION QUOTA UNLIMITED ON USERS;
ALTER USER ONNOVACION IDENTIFIED BY "12345";
SELECT DEFAULT_TABLESPACE FROM DBA_USERS WHERE USERNAME = 'ONNOVACION';

---------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------DROPS---------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------

DROP SEQUENCE ONNOVACION.MOVEMENT_id_seq;
DROP SEQUENCE ONNOVACION.ACCOUNT_id_seq;
DROP SEQUENCE ONNOVACION.CLIENT_id_seq;

DROP TRIGGER ONNOVACION.CONTROL_INSERT_ON_MOVEMENT;
DROP TRIGGER ONNOVACION.CONTROL_INSERT_ON_ACCOUNT;
DROP TRIGGER ONNOVACION.CONTROL_INSERT_ON_CLIENT;

DROP TABLE ONNOVACION.MOVEMENT;
DROP TABLE ONNOVACION.ACCOUNT;
DROP TABLE ONNOVACION.CLIENT;

DROP PACKAGE ONNOVACION.FUNCTIONS;

-------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------CLIENTS---------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE ONNOVACION.CLIENT_id_seq START WITH 1 MAXVALUE 1000000000 INCREMENT BY 1;

CREATE TABLE ONNOVACION.CLIENT (
	ID NUMBER NOT NULL,
	NAME VARCHAR2(80) NULL,
	LASTNAME VARCHAR2(250) NULL,
	DOCUMENTTYPE VARCHAR2(5) NULL CHECK (DOCUMENTTYPE IN ('CC', 'CE')),
	DOCUMENTNUMBER VARCHAR2(50) NULL,
	RUT VARCHAR2(50) NOT NULL UNIQUE,
	SOCIALREASON VARCHAR2(100) NULL,
	FUNDATIONYEAR NUMBER NULL CHECK (FUNDATIONYEAR >= 1800),
	CLIENTTYPE VARCHAR(1) NOT NULL CHECK (CLIENTTYPE IN ('N', 'J'))
);
ALTER TABLE ONNOVACION.CLIENT ADD CONSTRAINT "client_primary_key" PRIMARY KEY (ID);

CREATE OR REPLACE TRIGGER ONNOVACION.CONTROL_INSERT_ON_CLIENT 
BEFORE INSERT ON ONNOVACION.CLIENT
FOR EACH ROW
BEGIN
	:NEW.ID := ONNOVACION.CLIENT_id_seq.NEXTVAL;
END;

DELETE FROM ONNOVACION.CLIENT;

INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1', 'JUAN', 'MARTINEZ', 'CC', '1026150352', '30.686.957-X', NULL, NULL,'N');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1', 'JUAN', 'MARTINEZ', 'CC', '1026150352', '30.686.957-y', NULL, NULL,'N');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1', 'JUAN', 'MARTINEZ', 'CC', '1026150352', '30.686.957-Z', NULL, NULL,'N');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1', 'JUAN', 'MARTINEZ', 'CC', '1026150352', '30.686.957-A', NULL, NULL,'N');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1', 'JUAN', 'MARTINEZ', 'CC', '1026150352', '30.686.957-B', NULL, NULL,'N');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1',NULL,NULL,NULL,NULL,'30.686.957-C','ONNOVACION.SAS',2018,'J');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1',NULL,NULL,NULL,NULL,'30.686.957-D','ONNOVACION1.SAS',2018,'J');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1',NULL,NULL,NULL,NULL,'30.686.957-E','ONNOVACION2.SAS',2018,'J');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1',NULL,NULL,NULL,NULL,'30.686.957-F','ONNOVACION3.SAS',2018,'J');
INSERT INTO ONNOVACION.CLIENT (ID,NAME,LASTNAME,DOCUMENTTYPE,DOCUMENTNUMBER,RUT,SOCIALREASON,FUNDATIONYEAR,CLIENTTYPE) 
VALUES ('1',NULL,NULL,NULL,NULL,'30.686.957-G','ONNOVACION4.SAS',2018,'J');

-------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------ACCOUNTS--------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE ONNOVACION.ACCOUNT_id_seq START WITH 1 MAXVALUE 1000000000 INCREMENT BY 1;

CREATE TABLE ONNOVACION.ACCOUNT (
	ID NUMBER NOT NULL,
	CURRENCY VARCHAR2(80) NULL CHECK(CURRENCY IN ('PESO', 'EURO', 'DOLAR')),
	VALUE NUMBER NULL,
	CLIENT_ID NUMBER NOT NULL
);
ALTER TABLE ONNOVACION.ACCOUNT ADD CONSTRAINT "account_primary_key" PRIMARY KEY (ID);
ALTER TABLE ONNOVACION.ACCOUNT ADD CONSTRAINT "account_cliente_fk" FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID);

CREATE OR REPLACE TRIGGER ONNOVACION.CONTROL_INSERT_ON_ACCOUNT
BEFORE INSERT ON ONNOVACION.ACCOUNT
FOR EACH ROW
BEGIN
	:NEW.ID := ONNOVACION.ACCOUNT_id_seq.NEXTVAL;
END;

DELETE FROM ONNOVACION.ACCOUNT;

INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 500000, 1);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'EURO', 50000, 1);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'DOLAR', 300000, 2);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 1);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 3);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 3);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 500000, 8);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'EURO', 50000, 7);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'DOLAR', 300000, 8);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 8);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 9);
INSERT INTO ONNOVACION.ACCOUNT (ID, CURRENCY, VALUE, CLIENT_ID) VALUES (1,'PESO', 5000, 7);

------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------MOVEMENTS-------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE ONNOVACION.MOVEMENT_id_seq START WITH 1 MAXVALUE 1000000000 INCREMENT BY 1;

CREATE TABLE ONNOVACION.MOVEMENT (
	ID NUMBER NOT NULL,
	VALUE NUMBER NULL,
	ACCOUNT_ID NUMBER NOT NULL
);
ALTER TABLE ONNOVACION.MOVEMENT ADD CONSTRAINT "movements_primary_key" PRIMARY KEY (ID);
ALTER TABLE ONNOVACION.MOVEMENT ADD CONSTRAINT "movement_account_fk" FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

CREATE OR REPLACE TRIGGER ONNOVACION.CONTROL_INSERT_ON_MOVEMENT
BEFORE INSERT ON ONNOVACION.MOVEMENT
FOR EACH ROW
BEGIN
	:NEW.ID := ONNOVACION.MOVEMENT_id_seq.NEXTVAL;
END;

DELETE FROM ONNOVACION.MOVEMENT;

INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 2000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 1000, 11);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 8000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, -6000, 11);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, -5000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 9000, 11);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 12000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, -2000, 11);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 22000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 200, 11);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 30000, 10);
INSERT INTO ONNOVACION.MOVEMENT (ID, VALUE, ACCOUNT_ID) VALUES (1, 2500, 11);


SELECT * FROM ONNOVACION.MOVEMENT MOVEMENT
INNER JOIN ONNOVACION.ACCOUNT ACCOUNT ON MOVEMENT.ACCOUNT_ID  = ACCOUNT.ID
INNER JOIN ONNOVACION.CLIENT CLIENT ON ACCOUNT.CLIENT_ID = CLIENT.ID;

-----------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------PACKAGE---------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE ONNOVACION.FUNCTIONS IS
	 FUNCTION VALIDATEFIELDSINSERTONCLIENT
	 (ID IN ONNOVACION.CLIENT.ID%TYPE, NAME IN ONNOVACION.CLIENT.NAME%TYPE, 
	 LASTNAME IN ONNOVACION.CLIENT.LASTNAME%TYPE, DOCUMENTTYPE IN ONNOVACION.CLIENT.DOCUMENTTYPE%TYPE, 
	 DOCUMENTNUMBER IN ONNOVACION.CLIENT.DOCUMENTNUMBER%TYPE, RUT IN ONNOVACION.CLIENT.RUT%TYPE, 
	 SOCIALREASON IN ONNOVACION.CLIENT.SOCIALREASON%TYPE, FUNDATIONYEAR IN ONNOVACION.CLIENT.FUNDATIONYEAR%TYPE, 
	 CLIENTTYPE IN ONNOVACION.CLIENT.CLIENTTYPE%TYPE) RETURN VARCHAR;
	
	 FUNCTION VALIDATEACCOUNTVALUEAFTERMOVEMENT
 	 (VALUE IN ONNOVACION.MOVEMENT.VALUE%TYPE, ACCOUNT_ID IN ONNOVACION.MOVEMENT.ACCOUNT_ID%TYPE) RETURN VARCHAR;
 
  	 PROCEDURE UPDATEACCOUNTVALUEAFTERMOVEMENT
 	 (VALUE IN ONNOVACION.MOVEMENT.VALUE%TYPE, ACCOUNT_ID IN ONNOVACION.MOVEMENT.ACCOUNT_ID%TYPE);
END;

CREATE OR REPLACE PACKAGE BODY ONNOVACION.FUNCTIONS IS
	FUNCTION VALIDATEFIELDSINSERTONCLIENT
	(ID IN ONNOVACION.CLIENT.ID%TYPE, NAME IN ONNOVACION.CLIENT.NAME%TYPE, 
	LASTNAME IN ONNOVACION.CLIENT.LASTNAME%TYPE, DOCUMENTTYPE IN ONNOVACION.CLIENT.DOCUMENTTYPE%TYPE, 
	DOCUMENTNUMBER IN ONNOVACION.CLIENT.DOCUMENTNUMBER%TYPE, RUT IN ONNOVACION.CLIENT.RUT%TYPE, 
	SOCIALREASON IN ONNOVACION.CLIENT.SOCIALREASON%TYPE, FUNDATIONYEAR IN ONNOVACION.CLIENT.FUNDATIONYEAR%TYPE, 
	CLIENTTYPE IN ONNOVACION.CLIENT.CLIENTTYPE%TYPE) RETURN VARCHAR IS
	BEGIN	
		IF CLIENTTYPE = 'N' THEN
			IF ID IS NULL OR NAME IS NULL OR LASTNAME IS NULL OR DOCUMENTTYPE IS NULL 
			OR DOCUMENTNUMBER IS NULL
			OR RUT = NULL OR RUT = '' THEN
		  		RETURN 'FALSE';
		  	ELSE 
		  		RETURN 'TRUE';
		  	END IF;
		END IF;
		IF CLIENTTYPE = 'J' THEN
			IF SOCIALREASON IS NULL OR FUNDATIONYEAR IS NULL OR RUT IS NULL THEN
		  		RETURN 'FALSE';
		  	ELSE 
		  		RETURN 'TRUE';
		  	END IF;
		END IF;
	END;

	FUNCTION VALIDATEACCOUNTVALUEAFTERMOVEMENT
	(VALUE IN ONNOVACION.MOVEMENT.VALUE%TYPE, ACCOUNT_ID IN ONNOVACION.MOVEMENT.ACCOUNT_ID%TYPE) RETURN VARCHAR IS
		CURRENTACOUTVALUE NUMBER;
		ACCOUNTCURRENCY VARCHAR2(80);
	BEGIN
		SELECT ACCOUNT.VALUE INTO CURRENTACOUTVALUE FROM ONNOVACION.ACCOUNT ACCOUNT
		WHERE ACCOUNT.ID = ACCOUNT_ID;
	
		SELECT ACCOUNT.CURRENCY  INTO ACCOUNTCURRENCY FROM ONNOVACION.ACCOUNT ACCOUNT
		WHERE ACCOUNT.ID = ACCOUNT_ID;
	
		IF ACCOUNTCURRENCY = 'PESO' THEN
			IF CURRENTACOUTVALUE + VALUE = 1000000 THEN
				RETURN 'FALSE';
			END IF;
		END IF;
	
		IF ACCOUNTCURRENCY = 'EURO' THEN
			IF CURRENTACOUTVALUE + VALUE = 150 THEN
				RETURN 'FALSE';
			END IF;
		END IF;
	
		IF ACCOUNTCURRENCY = 'DOLAR' THEN
			IF CURRENTACOUTVALUE + VALUE = 300 THEN
				RETURN 'FALSE';
			END IF;
		END IF;
		RETURN 'TRUE';
	END;

	PROCEDURE UPDATEACCOUNTVALUEAFTERMOVEMENT
	(VALUE IN ONNOVACION.MOVEMENT.VALUE%TYPE, ACCOUNT_ID IN ONNOVACION.MOVEMENT.ACCOUNT_ID%TYPE) IS
		CURRENTACOUTVALUE NUMBER;
	BEGIN
		SELECT ACCOUNT.VALUE INTO CURRENTACOUTVALUE FROM ONNOVACION.ACCOUNT ACCOUNT
		WHERE ACCOUNT.ID = ACCOUNT_ID;
		CURRENTACOUTVALUE := CURRENTACOUTVALUE + VALUE;
		UPDATE ONNOVACION.ACCOUNT ACCOUNT SET ACCOUNT.VALUE = CURRENTACOUTVALUE WHERE ACCOUNT.ID = ACCOUNT_ID;
	END;
END;